version: '3.1'

services:
  db:
    container_name: db-pgsql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - vt
  redis:
    container_name: sc-redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - vt

networks:
  vt:
