spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    jdbc:
      audit: off
      resultset: off
      resultsettable: debug
      connection: off
      sqlonly: off
      sqltimming: debug
app:
  security:
    jwt:
      secret: sample
      limit: 1440
      issuer: localhost:8080
