= Clinic API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

NOTE: 동물병원과 관련된 api 입니다.

== 1. Admin API

=== 1.1 find by id
특정 동물병원을 조회합니다

operation::veterinary-clinic-admin-controller-test/find-by-id[snippets='path-parameters,http-request,http-response']

'''

=== 1.2 find all
동물병원을 리스트를 조회합니다

operation::veterinary-clinic-admin-controller-test/find-all[snippets='query-parameters,http-request,http-response']

'''

=== 1.3 save
신규 동물병원을 등록합니다

operation::veterinary-clinic-admin-controller-test/save[snippets='request-fields,http-request,http-response']

=== 1.4 delete
동물병원을 삭제(영업중지)합니다.

operation::veterinary-clinic-admin-controller-test/delete[snippets='request-fields,http-request,http-response']

== 2. Client API

=== 2.1 find
영업 중인 특정 동물병원을 찾습니다

operation::veterinary-clinic-client-controller-test/find[snippets='path-parameters,http-request,http-response']
operation::veterinary-clinic-client-controller-test/not-found[snippets='http-response']

'''

=== 2.2 update
동물병원 정보를 수정합니다

operation::veterinary-clinic-client-controller-test/update[snippets='request-fields,http-request,http-response']
