= Common API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

NOTE: 로그인 및 권한과 관련된 api 입니다.

== 1. Admin API

=== 1.1 login
시스템 관리자 계정으로 로그안합니다

operation::security-test/admin-user-login[snippets='request-fields,http-request,http-response']

'''

=== 1.2 reissue token
시스템 관리자 권한의 토큰을 재발급 합니다

operation::security-test/admin-user-reissue-token[snippets='request-fields,http-request,http-response']

'''

=== 1.3 request
시스템 관리자 권한이 필요한 API를 요청합니다

operation::security-test/admin-user-api-request[snippets='request-headers,http-request,http-response']

'''

=== 1.4 logout
시스템 관리자 계정을 로그아웃합니다

operation::security-test/admin-user-logout[snippets='request-headers,http-request,http-response']

== 2. Client API

=== 2.1 login
동물 병원 관리자로 로그인합니다

operation::security-test/client-user-login[snippets='request-fields,http-request,http-response']

'''

=== 2.2 reissue token
동물 병원 관리자 권한의 토큰을 재발급 합니다

operation::security-test/admin-user-reissue-token[snippets='request-fields,http-request,http-response']

'''

=== 2.3 request
동물 병원 관리자 권한이 필요한 API를 요청합니다

operation::security-test/client-user-api-request[snippets='request-headers,http-request,http-response']

'''

=== 2.4 logout
동물 병원 관리자 계정을 로그아웃합니다

operation::security-test/client-user-logout[snippets='request-headers,http-request,http-response']
